### ISSUE TITLE
Displaying reputation with organizations in star citizen

### ISSUE THREAD

**Issue by Esoteric-161** [Shin0by/StarCitizen-Helper#10]
After several launches, the reputation with organizations in the mobiglas game ceases to be displayed, after reinstalling it earned, but also after several launches, it stopped being displayed in the game again.

**Comment by Shin0by** [comment]
This is a known issue that we can't fix with small changes. The solution is simple, first launch StarCitizen Helper, then launch the game through the launcher. The launcher generates a session token and StarCitizen Helper will receive it. Alternatively, you can run the game with the launcher with the enabled mod, and then the game will quickly give an error, but the token will be updated, and you will not have to wait for the main menu to load. I recommend generating a token through the launcher at least once a day, or before long gaming sessions.
