### ISSUE TITLE
ошибка загрузки

### ISSUE THREAD

**Issue by graundver** [Shin0by/StarCitizen-Helper#12]
![1697796255299](https://github.com/Shin0by/StarCitizen-Helper/assets/148542011/a92ee8ad-8a1d-4121-8e97-b5fb60df1de8)

**Comment by Shin0by** [comment]
Сейчас весь наш трафик подвержен повышенному вниманию со стороны провайдеров и гос. структур. Так что подобная проблема возникает довольно часто. 
1 - Во вкладке [Система] поставить галочку [Игнорировать ошибки SSL\TLS сертификата GitHub] и перезапустить программу.
2 - Попробовать скачать локализацию  самому через брузер, ссылка как раз указана синим текстом (как вариант поставить и включить плагин с VPN под браузер, на момент скачивания). Загрузить оттуда файл [Source code (zip)] и указать к нему путь нажав кнопку на вкладке [Локализация] [Черная кнопка в виде папки].
3 - Если ничто не помогает, то обратиться к другим игрокам, попросить их скачать для вас файл локализации. Получив его укажите к нему путь нажав кнопку на вкладке [Локализация] [Черная кнопка в виде папки].
