### ISSUE TITLE
проблемы с программой

### ISSUE THREAD

**Issue by 4ertilas** [Shin0by/StarCitizen-Helper#3]
![Screenshot_55](https://user-images.githubusercontent.com/74901156/99944556-1f5c2e80-2d84-11eb-986a-7df3997c450b.png)

**Comment by Shin0by** [comment]
Обычно данная проблема связана с устаревшей (не обновленной) версией Windows.
Программа использует проверку сетртификата для скачиваемого ядра, а методы проверки могут быть устаревшими на уровне операционной системы.
