### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by MAKCOC1** [Shin0by/StarCitizen-Helper#4]
При запуске модификации появляется ошибка, сильно расписывать не буду, думаю вам и так всё понятно.
Спасибо кстати за модификацию, только благодаря ей я смог изучать игру самостоятельно.
Жду обратной связи по поводу ошибки, спасибо за ваше время
![0bn2rMI8NRE](https://user-images.githubusercontent.com/98140391/150463476-0b3651a9-e97a-42bc-9721-3047cb430616.jpg)

**Comment by Shin0by** [comment]
К сожалению мы все еще не наладили процесс верификации ядра с разработчиками. После введения Easy Anti Cheat у них был плотный график с новогодним патчем, распродажей и каникулами. Надеюсь, что скоро эту проблему удастся решить. Ну а пока это совершенно адекватная реакция  EAC на ядро локализации. Это сообщение будет возникать до момента добавления ядра в белый список, что затруднительно, так как порой мы обновляем ядро по 2 раза за сутки. То есть нам требуется не добавление статичного файла ядра в белый список, а отработка методов вместе с разработчиками, что бы регулярно и непрерывно добавлять новые версии ядра в белый список. Так что ждем наладки работы после нового года и методов взаимодействия в отношении ядра и разрабов.

**Comment by FenixMen** [comment]
Очень ждем решения этой ужасной ситуации))

**Comment by dimond82** [comment]
При запуске модификации 1.8.18.118 появляется ошибка "Ошибка при запуске приложения (0xc0000142). Для выхода из приложения нажми "OK". " Затем следующая ошибка  unknown file version (E:\Games\star citizen\live\bin64\dbghelp.dll). В приложении Star Citezen Helper 1.8.18.118 сказано что название файла CIGDevelopment.dll было заменено на dbghelp.dll. В данном случае проблема та же что и была 21 января? Надо ждать когда добавят ядро в белый список?

**Comment by atong9033** [comment]
Ребят,а немного непонятен смысл вашей работы если результат все равно нулевой. Зачем выпускать обновления к приложению, которое не работает? Или это задел на будущее?

**Comment by defterai** [comment]
Чтобы проще было это все устанавливать тем, кто занимается закрытым тестированием перевода, что нужно для поддержания актуальности перевода, шрифтов, и прочих ресурсов. И чтобы когда CIG дадут добро, все уже было в рабочем состоянии (не просто переведено, но и протестировано в игре) Поскольку ресурсы локализаторов на все языки ограниченные - проще работать в режиме когда каждый делает минимальный вклад регулярно, чем доганять потом все то что пропустили за длительное время. Все локализаторы работают в свободное удобное для них время, они не смогут выполнить тот же обьем работы что делается за год сейчас за короткое время если это будет нужно.

**Comment by Shin0by** [comment]
@defterai верно пишет. Мы тестируем всё закрыто. Рекомендовать наши методы обхода античита, мы не хотим, так как это может быть чревато баном. Мы рискуем, но ответственность за других брать не хотим. Ранее мы прсото включали возможность локализации (добавляя тем самым функционал к игре), а сейчас потребуется отключать античит (убрать часть имеющегося функционала игры), что будет прямым нарушением работоспособности того, что разработали CIG в последнее время.
Но мы продолжаем работу, актуализируем перевод и наш софт и как только нас внесут в белый список, всё будет уже готово к запуску локи.

**Comment by Shin0by** [comment]
> При запуске модификации 1.8.18.118 появляется ошибка "Ошибка при запуске приложения (0xc0000142). Для выхода из приложения нажми "OK". " Затем следующая ошибка unknown file version (E:\Games\star citizen\live\bin64\dbghelp.dll). В приложении Star Citezen Helper 1.8.18.118 сказано что название файла CIGDevelopment.dll было заменено на dbghelp.dll. В данном случае проблема та же что и была 21 января? Надо ждать когда добавят ядро в белый список?

Да, надо ждать белый список. Мы обновляем софт и локу, но делаем это для самих же локализаторов, что бы они могли переводить дальше и всё было готово, как только нас внесут в белый список. Рекомендовать методы обхода античит, мы не хотим, хоть они и есть.

Относительно первой ошибки "0xc0000142" - это не нормально. Рекомендую удалить софтину (для верности удалить ее папку: %appdata%\StarCitizen Helper), скачать заново последнюю версию и установить. Затем загрузить из репозитория последнюю версию локализации и попробовать включить и выключить ее. В игре лока не заработает, но ошибок при включении и выключении программа (StarCitizen Helper) выдавать не должна.

**Comment by Shin0by** [comment]
В методах запуска игры произошли изменения и все ранее описанные в этой теме ошибки, становятся не актуальны, либо будут вносить путаницу в связи с изменениями.
