### ISSUE TITLE
Всё тот же вопрос по поводу русификатора.

### ISSUE THREAD

**Issue by MAKCOC1** [Shin0by/StarCitizen-Helper#6]
Увидел что были обновления модификации, подскажите она уже заработала или всё так же?

**Comment by Shin0by** [comment]
Обновления делаем, что бы как только нас одобрят разработчики, у нас все было уже готово, в плане перевода. Ну и свои программы мы тоже по мелочам обновляем, если находим баги. В остальном же все пока без изменений. Судя по всему переезд разрабов сильно ударил по их общению с нами.
