### ISSUE TITLE
SC Modding: Failed post initialize

### ISSUE THREAD

**Issue by takoyaro** [Shin0by/StarCitizen-Helper#9]
Getting this error once I click on `Launch Game`
![image](https://user-images.githubusercontent.com/54836677/180917621-17629389-0ce0-4847-ae95-11c9188cb91b.png)
![ScreenShot-2022-07-26_12-38-11-635](https://user-images.githubusercontent.com/54836677/180917858-00c944d5-e798-4a89-a613-94a755ed997f.jpg)

**Comment by marona42** [comment]
It's related on core module. check the StarCitizen version.
the current module supports 3.17.1(PU), not the 3.17.2(PTU)
